name: tag

on:
  push:
    tags:
      - "v*.*.*"

env:
  GO_VERSION: 1.20.5

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o axiom-ledger-linux-amd64

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o axiom-ledger-darwin-amd64

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./axiom-ledger-linux-amd64
          asset_name: axiom-ledger-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./axiom-ledger-darwin-amd64
          asset_name: axiom-ledger-darwin-amd64
          asset_content_type: application/octet-stream

      - name: "If failure"
        id: check
        if: ${{ failure() }}
        run: echo "status=failure" >> $GITHUB_OUTPUT
